name: PHP to HTML Conversion

on:
  push:
    branches:
      - main  # This will run the action every time you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # You can specify the PHP version you need

    - name: Convert PHP to HTML
      run: |
        mkdir -p public
        php -r 'file_put_contents("public/test.html", file_get_contents("test.php"));'
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
